Remove testrunner package and update App setup
dogmatiq/example pull request #87
Opened 2020-11-16 07:13 UTC by koden-km

#### What change does this introduce?

This PR removes the `testrunner` package and `example.NewApp()` and constructs them inline as needed. The app setup for running and testing will be updated to match the newer setup style.

#### What issues does this relate to?

Fixes #77 

#### Why make this change?

The app setup procedure has evolved to be much simpler since this example project was initially built. This change will keep the example project similar to the real projects.

#### Is there anything you are unsure about?

Did I miss anything in the new style setup procedure?

2020-11-16 23:07 UTC, jmalloc requested changes

2020-11-16 23:07 UTC, jmalloc commented on projections/account_test.go
> +			}).
```suggestion
			testkit.New(&example.App{ReadDB: db}).
```

2020-11-17 06:39 UTC, danilvpetrov approved these changes

2020-11-19 07:15 UTC, jmalloc approved these changes

2020-11-19 07:33 UTC, merged