Use the ubiquitous language for daily debit limit
dogmatiq/example pull request #88
Opened 2020-11-16 11:57 UTC by koden-km

#### What change does this introduce?

This PR fixes some of the terminology used in the daily debit limit implementation to match the ubiquitous language.

#### What issues does this relate to?

Fixes #81 

#### Why make this change?

The language used in the domain should match the ubiquitous language as much as possible so that the domain experts and programmers understand each other.

#### Is there anything you are unsure about?

No.

2020-11-16 12:12 UTC, danilvpetrov commented on domain/dailydebitlimit.go
> +	// ConsumedAmount is the sum of debit amounts consumed during the period, in
"during the period" sounds like a certain period is implied, perhaps the period should be mentioned? E.g. `ConsumedAmount is the sum of debit amounts consumed during the daily period...`.  If there is no need to emphasise any particular period, perhaps it should sound like `ConsumedAmount is the sum of debit amounts consumed during a certain period...`

Also, I think you meant to use the amount in singular: 

```suggestion
	// ConsumedAmount is the sum of debit amount consumed during the period, in
```

2020-11-16 12:16 UTC, danilvpetrov commented on domain/dailydebitlimit.go
> +	// ConsumedAmount is the sum of debit amounts consumed during the period, in
Sorry I did not consider the top comment for the `dailyDebitLimit ` struct which mentions the daily limit and hence the daily period, you can disregard my first paragraph in the comment.

2020-11-16 22:42 UTC, jmalloc requested changes
I discussed the naming with @koden-km in person, and we came up with the changes within my review.

2020-11-16 22:42 UTC, jmalloc commented on domain/dailydebitlimit.go
> +	ConsumedAmount int64
```suggestion
	// TotalDebitsForDay is the total of all debits for the day, in cents.
	TotalDebitsForDay int64
```

2020-11-16 22:42 UTC, jmalloc commented on domain/dailydebitlimit.go
>  			LimitMaximum:  maximumDailyDebitLimit,
```suggestion
			TotalDebitsForDay: d.TotalDebitsForDay,
			DailyLimit:  maximumDailyDebitLimit,
```

2020-11-19 07:55 UTC, jmalloc approved these changes

2020-11-20 06:17 UTC, merged

2020-11-20 06:57 UTC, danilvpetrov reviewed
Looking good, sorry for a late review.